name: xmonad-config
version: "0.0.0"

language: GHC2021

ghc-options:
  - -Wall
  - -Wcpp-undef
  - -Werror
  - -Widentities
  - -Wincomplete-uni-patterns
  - -Wincomplete-record-updates
  - -Wpartial-fields
  - -Wredundant-constraints
  - -Wunused-packages

dependencies:
  - base > 4.18
  - xmonad

library:
  source-dirs: src
  exposed-modules:
    - XMonad.Config.Personal
  other-modules:
    - XMonad.Config.ScreenRatioDependentLayout
